# Generated by Django 5.0.1 on 2024-01-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='rt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
